[package]
name = "map-file-differ"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.74"
cpp_demangle = "0.4.2"
pest = "2.7.2"
pest_derive = "2.7.2"
